package pl;

import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;

/**
 *
 * @author Mustafa
 */
public class teacherMainForm extends javax.swing.JFrame {

    /**
     * Creates new form teacherMainForm
     */
    int id1;//ogretmen id almak için
    String nameSurname; //öğretmen ad soyad
    String Gemail;//gönderici email

    public teacherMainForm() {
        initComponents();
        addIcons();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCourses = new javax.swing.JButton();
        btnAssignments = new javax.swing.JButton();
        btnAnnouncements = new javax.swing.JButton();
        btnMessaging = new javax.swing.JButton();
        lblOturumInfo = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        lblIconCourse = new javax.swing.JLabel();
        lblIconAss = new javax.swing.JLabel();
        lblIconAnn = new javax.swing.JLabel();
        lblIconMess = new javax.swing.JLabel();
        lblIconLogout = new javax.swing.JLabel();
        btnStream = new javax.swing.JButton();
        lblIconStream = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teacher Main Page");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        btnCourses.setBackground(new java.awt.Color(255, 255, 102));
        btnCourses.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCourses.setText("Courses");
        btnCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoursesActionPerformed(evt);
            }
        });

        btnAssignments.setBackground(new java.awt.Color(255, 255, 102));
        btnAssignments.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAssignments.setText("Assignments");
        btnAssignments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignmentsActionPerformed(evt);
            }
        });

        btnAnnouncements.setBackground(new java.awt.Color(255, 255, 102));
        btnAnnouncements.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAnnouncements.setText("Announcements");
        btnAnnouncements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnouncementsActionPerformed(evt);
            }
        });

        btnMessaging.setBackground(new java.awt.Color(255, 255, 102));
        btnMessaging.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMessaging.setText("Messaging");
        btnMessaging.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMessagingActionPerformed(evt);
            }
        });

        lblOturumInfo.setBackground(new java.awt.Color(255, 255, 153));
        lblOturumInfo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblOturumInfo.setForeground(new java.awt.Color(0, 102, 102));

        btnLogout.setBackground(new java.awt.Color(255, 51, 51));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnStream.setBackground(new java.awt.Color(255, 255, 102));
        btnStream.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnStream.setText("Stream");
        btnStream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStreamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 71, Short.MAX_VALUE)
                .addComponent(lblOturumInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblIconCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(lblIconAss, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(lblIconAnn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(lblIconMess, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(lblIconStream, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMessaging, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAnnouncements, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(btnAssignments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCourses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStream, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(lblIconLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblOturumInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIconCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAssignments, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIconAss, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAnnouncements, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIconAnn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMessaging, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIconMess, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIconStream, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStream, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout)
                    .addComponent(lblIconLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addIcons() {
        lblIconCourse.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/couses.png")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
        lblIconAss.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/assignments.jpg")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
        lblIconAnn.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/announcements.jpg")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
        lblIconMess.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/messaging.png")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
        lblIconLogout.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.jpg")).getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH)));
        lblIconStream.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/stream.png")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));

    }


    private void btnAnnouncementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnouncementsActionPerformed
        // TODO add your handling code here:
        announcementsForm af = new announcementsForm();
        af.idt = id1; //öğretmen id aldı
        af.nameSurname = nameSurname;
        af.setVisible(true);
    }//GEN-LAST:event_btnAnnouncementsActionPerformed

    private void btnCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoursesActionPerformed
        // TODO add your handling code here:
        teacherCoursesForm tcf = new teacherCoursesForm();
        tcf.idd = id1;//öğretmen id aldı
        tcf.setVisible(true);
    }//GEN-LAST:event_btnCoursesActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        loginForm l = new loginForm();
        l.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnMessagingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMessagingActionPerformed
        // TODO add your handling code here:
        messagingForm mf = new messagingForm();
        mf.setVisible(true);
        mf.idtt = id1; //öğretmen id aldı
        mf.Gemail = Gemail; //email aldık        
    }//GEN-LAST:event_btnMessagingActionPerformed

    private void btnAssignmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignmentsActionPerformed
        // TODO add your handling code here:
        assignmentsForm asf = new assignmentsForm();
        asf.idt = id1;
        asf.setVisible(true);

    }//GEN-LAST:event_btnAssignmentsActionPerformed

    private void btnStreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStreamActionPerformed
        // TODO add your handling code here:
        teacherStreamForm tsf = new teacherStreamForm();
        tsf.tid = id1; //öğretmen id 
        tsf.ogretmenInfo = nameSurname;//öğretmen isim soyisim 
        tsf.setVisible(true);
    }//GEN-LAST:event_btnStreamActionPerformed

    /**
     * @param args the command line arguments
     */
    //oturum açıldığında yazılan bilgiler
    public void oturumInfo(int id, String name, String surname) {
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        Date time = new Date();
        lblOturumInfo.setText("id:" + id + " " + name + " " + surname + "  \t\tLast Login=" + formatter.format(time));
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacherMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacherMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacherMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacherMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacherMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnouncements;
    private javax.swing.JButton btnAssignments;
    private javax.swing.JButton btnCourses;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMessaging;
    private javax.swing.JButton btnStream;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIconAnn;
    private javax.swing.JLabel lblIconAss;
    private javax.swing.JLabel lblIconCourse;
    private javax.swing.JLabel lblIconLogout;
    private javax.swing.JLabel lblIconMess;
    private javax.swing.JLabel lblIconStream;
    private javax.swing.JLabel lblOturumInfo;
    // End of variables declaration//GEN-END:variables
}
